name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/jseitter/jfat/packages
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Set version from release tag
      if: github.event_name == 'release'
      run: |
        # Extract version from tag and sanitize it
        RAW_VERSION=${GITHUB_REF#refs/tags/}
        # Remove 'v' prefix if present
        RAW_VERSION=${RAW_VERSION#v}
        # Replace any slashes with dots (not allowed in Maven versions)
        VERSION=$(echo "$RAW_VERSION" | sed 's|/|.|g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Release version: $VERSION (from tag: ${GITHUB_REF#refs/tags/})"
    
    - name: Set version from input
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Sanitize manual input version
        RAW_VERSION="${{ github.event.inputs.version }}"
        # Replace any slashes with dots (not allowed in Maven versions)
        VERSION=$(echo "$RAW_VERSION" | sed 's|/|.|g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Manual release version: $VERSION"
    
    - name: Validate version format
      run: |
        # Ensure version is not empty and contains only valid characters
        if [[ -z "$VERSION" ]]; then
          echo "Error: VERSION is empty"
          exit 1
        fi
        
        # Check for invalid characters (no slashes, spaces, etc.)
        if [[ "$VERSION" =~ [[:space:]/\\] ]]; then
          echo "Error: VERSION contains invalid characters: $VERSION"
          exit 1
        fi
        
        echo "✅ Version validation passed: $VERSION"
    
    - name: Update version in version.txt
      run: |
        # Simply write the version to version.txt (no sed needed!)
        echo "Current version.txt content:"
        cat version.txt || echo "(file does not exist)"
        
        echo "Writing version: $VERSION"
        echo "$VERSION" > version.txt
        
        echo "Updated version.txt content:"
        cat version.txt
        
        echo "Verifying Gradle can read the version:"
        ./gradlew properties | grep "^version:" || echo "Could not verify version"
    
    - name: Run tests before release
      run: ./gradlew test
    
    - name: Build release artifacts
      run: ./gradlew build -x test
    
    - name: Generate Javadoc
      run: ./gradlew javadoc
    
    - name: Create sources JAR
      run: ./gradlew sourcesJar
    
    - name: Create Javadoc JAR
      run: ./gradlew javadocJar
    
    - name: Publish to GitHub Package Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        ./gradlew publishAllPublicationsToGitHubPackagesRepository
    
    - name: Upload release artifacts
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/libs/jfat-${{ env.VERSION }}.jar
        asset_name: jfat-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive
    
    - name: Upload sources JAR to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/libs/jfat-${{ env.VERSION }}-sources.jar
        asset_name: jfat-${{ env.VERSION }}-sources.jar
        asset_content_type: application/java-archive
    
    - name: Upload Javadoc JAR to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/libs/jfat-${{ env.VERSION }}-javadoc.jar
        asset_name: jfat-${{ env.VERSION }}-javadoc.jar
        asset_content_type: application/java-archive
    
    - name: Create release summary
      run: |
        echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "- **Artifacts**: Main JAR, Sources JAR, Javadoc JAR" >> $GITHUB_STEP_SUMMARY
        echo "- **Published to**: GitHub Package Registry" >> $GITHUB_STEP_SUMMARY
        echo "- **Java Compatibility**: Java 11+" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: Production" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Usage" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`gradle" >> $GITHUB_STEP_SUMMARY
        echo "dependencies {" >> $GITHUB_STEP_SUMMARY
        echo "    implementation 'net.seitter.jfat:jfat:$VERSION'" >> $GITHUB_STEP_SUMMARY
        echo "}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 